apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-devops-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-devops-service
                port:
                  number: 8080
