apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devops-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-devops-app
  template:
    metadata:
      labels:
        app: java-devops-app
    spec:
      containers:
        - name: java-devops-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
