apiVersion: v1
kind: Service
metadata:
  name: java-devops-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: java-devops-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
